replicaCount: 1

image:
  repository: "<YOUR_REGISTRY>/<YOUR_REPO>/database-service"
  tag: "latest"
  pullPolicy: IfNotPresent
  # If using a private registry, configure imagePullSecrets
  imagePullSecrets: []

service:
  type: ClusterIP
  port: 8000

env:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "database_service"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
