replicaCount: 1

image:
  repository: "kaushikpaul90/db-service"
  tag: latest
  pullPolicy: IfNotPresent

db:
  host: "postgres"
  port: "5432"
  database: "ecommerce_db"
  user: "postgres"
  password: "postgres"

service:
  type: NodePort
  port: 8080 # inside cluster
  nodePort: 30000 # optional, else k8s will auto-assign

containerPort: 8000

resources: {}

persistence:
  enabled: false
  size: 5Gi

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
