replicaCount: 1

image:
  repository: "${DOCKER_HUB_USERNAME}/db-service"
  tag: latest
  pullPolicy: IfNotPresent

db:
  host: "postgres"
  port: "${DB_PORT}"
  database: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"

service:
  type: NodePort
  port: 8080 # inside cluster
  nodePort: 30000 # optional, else k8s will auto-assign

containerPort: 8000

resources: {}

persistence:
  enabled: false
  size: 5Gi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
