apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db-service.fullname" . }}
  labels:
    app: {{ include "db-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "db-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "db-service.name" . }}
    spec:
      containers:
        - name: db-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy | default "IfNotPresent" }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: "{{ .Values.db.host }}"
            - name: DB_PORT
              value: "{{ .Values.db.port }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-service.fullname" . }}-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-service.fullname" . }}-secret
                  key: db-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-service.fullname" . }}-secret
                  key: db-database
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
