apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db-service.fullname" . }}
  labels:
    app: {{ include "db-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "db-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "db-service.name" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-service.fullname" . }}-secret
                  key: postgres-database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-service.fullname" . }}-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "db-service.fullname" . }}-secret
                  key: postgres-password
